### ISSUE TITLE
NumPy 2.0

### ISSUE THREAD

**Issue by MehdiChinoune** [moderngl/moderngl-window#193]
Support numpy 2.x

**Comment by einarf** [comment]
Let's keep this around. We can bump it in 3.0

**Comment by einarf** [comment]
Likely you can lock your local version to numpy 2. Are there any compatibility issues with that?

**Comment by MehdiChinoune** [comment]
I am a packager for MSYS2, we could only have one version for NumPy.
The only solution right now is to drop your project.

**Comment by einarf** [comment]
Let me also help you out no how to get issues like this resolved fast. The original post can look something like this.

> Hi. I'm a packager for MSYS2 and your project only supports numpy 1.x. For this package to be included we need a version that uses numpy `>= 2. We can only support one version of numpy.

This lets the maintainers know that the issue might have some urgency and they will pick it for the next point release.

**Comment by MehdiChinoune** [comment]
I don't have to specify any details, It's known that many platforms package Python packages (Linux, Homebrew, MSYS2, *BSD...).
Anyone maintaining a Python project should be aware of that and keep his project up-to-date (Of course if he wants his project to be useful for other people).

**Comment by einarf** [comment]
A lot of people will be stuck with numpy 1 for a long time (years). It takes time to port over code because there are so many breaking changes. You might not know how different they are. Remember that numpy 2.0.0 was released a month ago and most don't jump on a `.0.0` version directly. They give it time to mature a little bit. It's mainly fresh projects that would go for numpy 2 at this point. That will of course change over time. 

We can't force numpy 2 or we will break most user code. We can make library version agnostic working with np 1 and 2 by loosening up the requirements and let the user decide. That requires some work and was planned for 3.0 initially.

The problem you are having is very specific to platforms packages. Everything have to be in lockstep. Most users get their packages from PyPI and install them in virtual environments and won't have this problem. I'm wondering if the jump to numpy 2 is a bit premature. At least for our user base it is.

I highly disagree about no needing to clarify basic details. When you request a change it's in most cases essential to know the reason why the change is needed in order to make the right decisions. In my 20+ years of open source I have never touched a request that didn't contain this information. This is one of those issues were context is very important because we don't normally think about platform packages.

**Comment by MehdiChinoune** [comment]
Most maintained projects have already moved to NumPy 2.0 (SciPy, Numba, Panda...).
I am closing this issue, Please don't reopen because I don't want to get any notification again.

**Comment by MehdiChinoune** [comment]
NumPy has an open issue about porting to NumPy 2.0
https://github.com/numpy/numpy/issues/26191
Those projects started porting to NumPy-2 when It was at RC stage, but some people were living in a cave.

**Comment by einarf** [comment]
Let's reopen this issue then. Like I said, we can probably support it just fine i 2.5, but there are no resources and time right now to make it happen on the spot. People are on vacation and/or are busy pushing new major releases of other projects. We're not part of a big organization. It's just two dudes with families and kids and other random contributors.

It will happen. It's already scheduled for 3.0 but since you are pressing the issue it could go in in 2.5 very soon.

**Comment by MehdiChinoune** [comment]
No longer an issue for us.
I upgraded numpy to 2.0.1.
The package builds. whether it runs or not is not my concern if the developer couldn't make his project compatible with numpy-2.

Please don't re-open.
Open a separate issue to track it.
